core/urls.py
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog
from .views import HomePage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('docs/', include("docs.urls")),
    path('', HomePage.as_view(), name='homepage'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docs/urls.py
from django.urls import path

from .views import TopicsView

app_name = "docs"
urlpatterns = [
    path('<int:pk>/', TopicsView.as_view(), name='topics'),
]

docs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from ckeditor.fields import RichTextField


class TopicManager(models.Manager):

    def available(self):
        return self.filter(active=True)

    def main_topics(self):
        return self.filter(parent__isnull=True)

    def available_main_topics(self):
        return self.filter(active=True, parent__isnull=True)


class Topic(models.Model):
    parent = models.ForeignKey('self', blank=True, null=True, related_name='subtopics', on_delete=models.SET_NULL,
                               limit_choices_to=models.Q(parent__isnull=True), verbose_name=_("Related To"))
    title = models.CharField(max_length=250, verbose_name=_("Title"))
    active = models.BooleanField(default=True, verbose_name=_('Active'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('Creation Date'))
    updated = models.DateTimeField(auto_now=True, verbose_name=_('Update Date'))

    objects = TopicManager()

    class Meta:
        verbose_name = _("Topic")
        verbose_name_plural = _("Topics")

    def __str__(self):
        return self.title


class SectionManager(models.Manager):

    def available(self):
        return self.filter(active=True)


class Section(models.Model):
    topic = models.ForeignKey(Topic, null=True, blank=False, related_name="sections", on_delete=models.SET_NULL,
                              limit_choices_to=models.Q(parent__isnull=False), verbose_name=_('Topic'))
    title = models.CharField(max_length=250, verbose_name=_("Title"))
    description = RichTextField(null=True, verbose_name=_("Description"))
    active = models.BooleanField(default=True, verbose_name=_('Active'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('Creation Date'))
    updated = models.DateTimeField(auto_now=True, verbose_name=_('Update Date'))

    objects = TopicManager()

    class Meta:
        verbose_name = _("Section")
        verbose_name_plural = _("Sections")

    def __str__(self):
        return self.title

core/views.py
from http import HTTPStatus

from django.shortcuts import render
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'home.html'


def page_not_found_view(request, exception=None):
    context = {
        'status': HTTPStatus.NOT_FOUND.real,
        'message': 'Page Not Found'
    }
    return render(request, "errors/404.html", context, status=context.get('status', None))


def error_view(request, exception=None):
    context = {
        'status': HTTPStatus.INTERNAL_SERVER_ERROR.real,
        'message': 'An error happens in our backend, if it continues, please get in touch with us as soon as possible'
    }
    return render(request, "errors/500.html", context, status=context.get('status', None))


def permission_denied_view(request, exception=None):
    context = {
        'status': HTTPStatus.FORBIDDEN.real,
        'message': 'You are not authorized to view this page or do this action'
    }
    return render(request, "errors/403.html", context, status=context.get('status', None))


def bad_request_view(request, exception=None):
    context = {
        'status': HTTPStatus.BAD_REQUEST.real,
        'message': 'Our server cannot or will not process the request due to something that is perceived to be a client error'
    }
    return render(request, "errors/400.html", context, status=context.get('status', None))

docs/views.py
from django.views.generic.detail import DetailView

from .models import Topic


class TopicsView(DetailView):
    model = Topic
    queryset = Topic.objects.available_main_topics()
    context_object_name = 'current_topic'
    template_name = 'docs/docs.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_topics'] = self.get_queryset()
        return context

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo.png' %}">
    <title>{% block title %} TimeCore | {% block subtitle %} Home {% endblock %} {% endblock %}</title>
    {% include 'base/css.html' %}
    {% block extra_style %} {% endblock %}
</head>
<body>
{% block body %}
<!--    {% include 'base/nav.html' %}-->
    {% include 'base/messages.html' %}

    {% block content %}
    {% endblock %}

<!--    {% include 'base/footer.html' %}-->
    {% include 'base/js.html' %}

    {% block extra_js %}
    {% endblock %}
{% endblock %}
</body>
</html>

templates/base/css.html
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous" referrerpolicy="no-referrer"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu:300,300i,400,400i,500,500i,700,700i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
<link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu:300,300i,400,400i,500,500i,700,700i|PT+Sans:400,400i,700,700i">

<link rel="stylesheet" href="{% static 'css/messages.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}" media="screen">
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<link rel="stylesheet" href="{% static 'css/extra.css' %}">

templates/base/footer.html
<footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-e3f5">
    <div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1">Sample text. Click to select the text box. Click again or double click to start editing the text.</p>
    </div>
</footer>
<section class="u-backlink u-clearfix u-grey-80">
    <a class="u-link" href="website-templates" target="_blank">
        <span>Free Website Templates</span>
    </a>
    <p class="u-text">
        <span>created with</span>
    </p>
    <a class="u-link" href="static-site-generator" target="_blank">
        <span>Static Site Generator</span>
    </a>.
</section>

templates/base/js.html
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script class="u-script" type="text/javascript" src="{% static 'js/jquery-1.9.1.min.js' %}" defer=""></script>
<script class="u-script" type="text/javascript" src="{% static 'js/app.js' %}" defer=""></script>

templates/base/messages.html
{% if messages %}

<!-- Messages Section -->
<div class="container-fluid position-fixed d-flex justify-content-start align-items-end flex-column gap-1 alert-container">
    {% for message in messages %}
        <div class="alert">
            <span class="close" onclick="this.parentElement.style.display='none';">&times;</span>
             {{ message }}
        </div>
    {% endfor %}
</div>
{% endif %}

templates/base/nav.html
{% load static %}

templates/docs/docs.html
{% include 'base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" href="{% static 'css/docs.css' %}">
{% endblock %}

{% block content %}
<div class="d-flex" id="wrapper">
    <!-- Sidebar-->
    <div class="border-end bg-white" id="sidebar-wrapper" style="background-color: #343131 !important;">
        <div class="sidebar-heading border-bottom bg-light" style="background-color: #343131 !important; color: #d9d9d9">Documentation</div>
        {% for topic in all_topics %}
        <div class="list-group list-group-flush d-flex flex-column" style="background-color: #e9e9e9;">
            <a href="#" class="d-flex align-items-center px-4 py-2 text-decoration-none text-dark dBtn">
                <i class="dropIcon me-2 fa-regular fa-square-plus"></i> {{ topic.title }}
            </a>
            {% for subtopic in topic.subtopics.available %}
            <div class="d-flex flex-column d-none dropDown">
                <a href="{% url 'docs:topics' topic.id %}#{{ topic.id }}-{{ subtopic.id }}" class="text-decoration-none text-dark px-4 py-2 ps-5 dropLink">{{ subtopic.title }}</a>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
    <!-- Page content wrapper-->
    <div id="page-content-wrapper">
        <!-- Top navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
            <div class="container-fluid">
                <button class="btn btn-primary" id="sidebarToggle" style="background: none; border:none; color: grey;"><i class="fas fa-bars"></i></button>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container-fluid">
            <h1>{{ current_topic.title }}</h1><hr>
            {% for topic in current_topic.subtopics.available %}
            <h2 id="{{ current_topic.id }}-{{ topic.id }}">{{ topic.title }}</h2>
                {% for section in topic.sections.available %}
                <h4>{{ section.title }}</h4>
                    {{ section.description|safe }}
                {% endfor %}
            <hr>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/docs.js' %}"></script>
{% endblock %}

templates/docs/new_docs.html
{% include 'base.html' %}
{% load static %}

{% block extra_style %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
<link rel="stylesheet" href="{% static 'css/new_docs.css' %}">
{% endblock %}


{% block content %}
<div class="side-bar">
    <div class="menu">
        <div class="item"><a href="#"><i class="fas fa-desktop"></i>Dashboard</a></div>
        <div class="item">
            <a class="sub-btn"><i class="fas fa-table"></i>Tables<i class="fas fa-angle-right dropdown"></i></a>
            <div class="sub-menu">
                <a href="#" class="sub-item">Sub Item 01</a>
                <a href="#" class="sub-item">Sub Item 02</a>
                <a href="#" class="sub-item">Sub Item 03</a>
            </div>
        </div>
        <div class="item"><a href="#"><i class="fas fa-th"></i>Forms</a></div>
        <div class="item">
            <a class="sub-btn"><i class="fas fa-cogs"></i>Settings<i class="fas fa-angle-right dropdown"></i></a>
            <div class="sub-menu">
                <a href="#" class="sub-item">Sub Item 01</a>
                <a href="#" class="sub-item">Sub Item 02</a>
            </div>
        </div>
        <div class="item"><a href="#"><i class="fas fa-info-circle"></i>About</a></div>
    </div>
</div>
<section class="main">
    <h1>Sidebar Menu With<br>Sub-Menus</h1>
</section>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8"></script>
<script type="text/javascript">
    $(document).ready(function () {
        //jquery for toggle sub menus
        $('.sub-btn').click(function () {
            $(this).next('.sub-menu').slideToggle();
            $(this).find('.dropdown').toggleClass('rotate');
        });
        //jquery for expand and collapse the sidebar
        $('.side-bar').addClass('active');
    });
</script>
{% endblock %}